var h,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},da="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ea=function(a,b){if(b){var c=da;a=a.split(".");
for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}};
ea("Promise",function(a){function b(){this.ka=null}function c(g){return g instanceof e?g:new e(function(k){k(g)})}if(a)return a;b.prototype.wc=function(g){if(null==this.ka){this.ka=[];var k=this;this.xc(function(){k.Cd()})}this.ka.push(g)};var d=da.setTimeout;b.prototype.xc=function(g){d(g,0)};b.prototype.Cd=function(){for(;this.ka&&this.ka.length;){var g=this.ka;this.ka=[];for(var k=0;k<g.length;++k){var l=g[k];g[k]=null;try{l()}catch(m){this.td(m)}}}this.ka=null};b.prototype.td=function(g){this.xc(function(){throw g;
})};var e=function(g){this.f=0;this.L=void 0;this.Qa=[];var k=this.Rb();try{g(k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.Rb=function(){function g(m){return function(n){l||(l=!0,m.call(k,n))}}var k=this,l=!1;return{resolve:g(this.Sd),reject:g(this.nc)}};e.prototype.Sd=function(g){if(g===this)this.nc(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof e)this.Vd(g);else{a:switch(typeof g){case "object":var k=null!=g;break a;case "function":k=!0;break a;default:k=!1}k?
this.Rd(g):this.Rc(g)}};e.prototype.Rd=function(g){var k=void 0;try{k=g.then}catch(l){this.nc(l);return}"function"==typeof k?this.Wd(k,g):this.Rc(g)};e.prototype.nc=function(g){this.jd(2,g)};e.prototype.Rc=function(g){this.jd(1,g)};e.prototype.jd=function(g,k){if(0!=this.f)throw Error("Cannot settle("+g+", "+k+"): Promise already settled in state"+this.f);this.f=g;this.L=k;this.Ed()};e.prototype.Ed=function(){if(null!=this.Qa){for(var g=0;g<this.Qa.length;++g)f.wc(this.Qa[g]);this.Qa=null}};var f=
new b;e.prototype.Vd=function(g){var k=this.Rb();g.ob(k.resolve,k.reject)};e.prototype.Wd=function(g,k){var l=this.Rb();try{g.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};e.prototype.then=function(g,k){function l(A,B){return"function"==typeof A?function(zb){try{m(A(zb))}catch(Ab){n(Ab)}}:B}var m,n,la=new e(function(A,B){m=A;n=B});this.ob(l(g,m),l(k,n));return la};e.prototype["catch"]=function(g){return this.then(void 0,g)};e.prototype.ob=function(g,k){function l(){switch(m.f){case 1:g(m.L);break;
case 2:k(m.L);break;default:throw Error("Unexpected state: "+m.f);}}var m=this;null==this.Qa?f.wc(l):this.Qa.push(l)};e.resolve=c;e.reject=function(g){return new e(function(k,l){l(g)})};e.race=function(g){return new e(function(k,l){for(var m=ba(g),n=m.next();!n.done;n=m.next())c(n.value).ob(k,l)})};e.all=function(g){var k=ba(g),l=k.next();return l.done?c([]):new e(function(m,n){function la(zb){return function(Ab){A[zb]=Ab;B--;0==B&&m(A)}}var A=[],B=0;do A.push(void 0),B++,c(l.value).ob(la(A.length-
1),n),l=k.next();while(!l.done)})};return e});
var fa=fa||{},p=this||self,q=function(a){return void 0!==a},r=function(a){return"string"==typeof a},ha=function(a){return"number"==typeof a},ia=function(a,b,c){a=a.split(".");c=c||p;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&q(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}},ja=function(a,b){a=a.split(".");b=b||p;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b},ka=function(){},t=function(a){var b=
typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},u=function(a){return"array"==t(a)},ma=function(a){var b=t(a);return"array"==b||"object"==b&&"number"==typeof a.length},v=function(a){return"function"==t(a)},w=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},pa=function(a){return a[na]||(a[na]=++oa)},na="closure_uid_"+(1E9*Math.random()>>>0),oa=0,qa=function(a,b,c){return a.call.apply(a.bind,arguments)},ra=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=
Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},x=function(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?qa:ra;return x.apply(null,arguments)},sa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},ta=
Date.now||function(){return+new Date},y=function(a,b){function c(){}c.prototype=b.prototype;a.G=b.prototype;a.prototype=new c;a.prototype.constructor=a};var z=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};y(z,Error);z.prototype.name="CustomError";var ua;var va=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");z.call(this,c+a[d])};y(va,z);va.prototype.name="AssertionError";
var wa=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new va(""+e,f||[]);},C=function(a,b,c){a||wa("",null,b,Array.prototype.slice.call(arguments,2));return a},D=function(a,b){throw new va("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},xa=function(a,b,c){ha(a)||wa("Expected number but got %s: %s.",[t(a),a],b,Array.prototype.slice.call(arguments,2));return a},ya=function(a,b,c){v(a)||wa("Expected function but got %s: %s.",[t(a),
a],b,Array.prototype.slice.call(arguments,2))};var za=Array.prototype.indexOf?function(a,b){C(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(r(a))return r(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Aa=Array.prototype.forEach?function(a,b,c){C(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ba=Array.prototype.map?function(a,b){C(null!=a.length);return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=r(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},Ca=Array.prototype.some?function(a,b){C(null!=a.length);return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},Ea=function(a){a:{var b=Da;for(var c=a.length,d=r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?
null:r(a)?a.charAt(b):a[b]},Fa=function(a,b){b=za(a,b);var c;if(c=0<=b)C(null!=a.length),Array.prototype.splice.call(a,b,1);return c},Ga=function(a){return Array.prototype.concat.apply([],arguments)},Ha=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ja=function(a,b){a.sort(b||Ia)},Ia=function(a,b){return a>b?1:a<b?-1:0};var Ka=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},La=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1},Ma=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Na="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Oa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Na.length;f++)c=Na[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Pa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};var E=function(a,b){this.tc=a===Qa&&b||"";this.qd=Ra};E.prototype.ha=!0;E.prototype.T=function(){return this.tc};E.prototype.toString=function(){return"Const{"+this.tc+"}"};var Sa=function(a){if(a instanceof E&&a.constructor===E&&a.qd===Ra)return a.tc;D("expected object of type Const, got '"+a+"'");return"type_error:Const"},Ra={},Qa={},Ta=new E(Qa,"");var Ua=function(){this.kc=""};Ua.prototype.ha=!0;Ua.prototype.T=function(){return this.kc.toString()};Ua.prototype.toString=function(){return"SafeScript{"+this.kc+"}"};Ua.prototype.pa=function(a){this.kc=a;return this};(new Ua).pa("");var Wa=function(){this.Ab="";this.ld=null;this.rd=Va};h=Wa.prototype;h.ha=!0;h.T=function(){return this.Ab.toString()};h.Yb=!0;h.Ka=function(){return 1};h.toString=function(){return"TrustedResourceUrl{"+this.Ab+"}"};var Xa=function(a){if(a instanceof Wa&&a.constructor===Wa&&a.rd===Va)return a.Ab;D("expected object of type TrustedResourceUrl, got '"+a+"' of type "+t(a));return"type_error:TrustedResourceUrl"},Va={};var Ya=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},fb=function(a){if(!Za.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace($a,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ab,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(bb,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(cb,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(db,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(eb,"&#0;"));return a},$a=/&/g,ab=/</g,bb=/>/g,cb=/"/g,db=/'/g,eb=/\x00/g,Za=
/[\x00&<>"']/,gb=function(a,b){return a<b?-1:a>b?1:0};var ib=function(){this.zb="";this.pd=hb};h=ib.prototype;h.ha=!0;h.T=function(){return this.zb.toString()};h.Yb=!0;h.Ka=function(){return 1};h.toString=function(){return"SafeUrl{"+this.zb+"}"};
var jb=function(a){if(a instanceof ib&&a.constructor===ib&&a.pd===hb)return a.zb;D("expected object of type SafeUrl, got '"+a+"' of type "+t(a));return"type_error:SafeUrl"},kb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,mb=function(a){if(a instanceof ib)return a;a="object"==typeof a&&a.ha?a.T():String(a);kb.test(a)||(a="about:invalid#zClosurez");return lb(a)},hb={},lb=function(a){var b=new ib;b.zb=a;return b};lb("about:blank");var F=function(){this.yb="";this.od=nb};F.prototype.ha=!0;var nb={};F.prototype.T=function(){return this.yb};F.prototype.toString=function(){return"SafeStyle{"+this.yb+"}"};F.prototype.pa=function(a){this.yb=a;return this};
var ob=(new F).pa(""),qb=function(a){if(a instanceof ib)return'url("'+jb(a).toString().replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';a=a instanceof E?Sa(a):pb(String(a));if(/[{;}]/.test(a))throw new va("Value does not allow [{;}], got: %s.",[a]);return a},pb=function(a){var b=a.replace(rb,"$1").replace(rb,"$1").replace(sb,"url");if(tb.test(b)){if(ub.test(a))return D("String value disallows comments, got: "+a),"zClosurez";for(var c=b=!0,d=0;d<a.length;d++){var e=a.charAt(d);"'"==e&&c?b=!b:'"'==
e&&b&&(c=!c)}if(!b||!c)return D("String value requires balanced quotes, got: "+a),"zClosurez";if(!vb(a))return D("String value requires balanced square brackets and one identifier per pair of brackets, got: "+a),"zClosurez"}else return D("String value allows only [-,.\"'%_!# a-zA-Z0-9\\[\\]] and simple functions, got: "+a),"zClosurez";return wb(a)},vb=function(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var e=a.charAt(d);if("]"==e){if(b)return!1;b=!0}else if("["==e){if(!b)return!1;b=!1}else if(!b&&
!c.test(e))return!1}return b},tb=/^[-,."'%_!# a-zA-Z0-9\[\]]+$/,sb=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g,rb=/\b(hsl|hsla|rgb|rgba|matrix|calc|minmax|fit-content|repeat|(rotate|scale|translate)(X|Y|Z|3d)?)\([-+*/0-9a-z.%\[\], ]+\)/g,ub=/\/\*/,wb=function(a){return a.replace(sb,function(b,c,d,e){var f="";d=d.replace(/^(['"])(.*)\1$/,function(g,k,l){f=k;return l});b=mb(d).T();return c+f+b+f+e})};var xb=function(){this.lc=""};xb.prototype.ha=!0;xb.prototype.T=function(){return this.lc};xb.prototype.toString=function(){return"SafeStyleSheet{"+this.lc+"}"};xb.prototype.pa=function(a){this.lc=a;return this};(new xb).pa("");var G;a:{var yb=p.navigator;if(yb){var Bb=yb.userAgent;if(Bb){G=Bb;break a}}G=""}var H=function(a){return-1!=G.indexOf(a)};var Db=function(){this.xb="";this.nd=Cb;this.Mc=null};h=Db.prototype;h.Yb=!0;h.Ka=function(){return this.Mc};h.ha=!0;h.T=function(){return this.xb.toString()};h.toString=function(){return"SafeHtml{"+this.xb+"}"};
var Eb=function(a){if(a instanceof Db&&a.constructor===Db&&a.nd===Cb)return a.xb;D("expected object of type SafeHtml, got '"+a+"' of type "+t(a));return"type_error:SafeHtml"},Gb=function(a){if(a instanceof Db)return a;var b="object"==typeof a,c=null;b&&a.Yb&&(c=a.Ka());return Fb(fb(b&&a.ha?a.T():String(a)),c)},Hb=/^[a-zA-Z0-9-]+$/,Ib={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},Kb=function(a){var b=Gb(Jb),c=b.Ka(),d=[],e=function(f){u(f)?Aa(f,e):(f=Gb(f),d.push(Eb(f).toString()),
f=f.Ka(),0==c?c=f:0!=f&&c!=f&&(c=null))};Aa(a,e);return Fb(d.join(Eb(b).toString()),c)},Lb=function(a){return Kb(Array.prototype.slice.call(arguments))},Cb={},Fb=function(a,b){return(new Db).pa(a,b)};Db.prototype.pa=function(a,b){this.xb=a;this.Mc=b;return this};Fb("<!DOCTYPE html>",0);var Jb=Fb("",0);Fb("<br>",0);var Mb={MATH:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0},Nb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if("undefined"===typeof document)return!1;var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);if(!a.firstChild)return!1;b=a.firstChild.firstChild;a.innerHTML=Eb(Jb);return!b.parentElement}),Ob=function(a){var b=Sa(Ta),c=new Wa;c.Ab=b;a:{try{var d=a&&a.ownerDocument,e=d&&(d.defaultView||
d.parentWindow);e=e||p;if(e.Element&&e.Location){var f=e;break a}}catch(k){}f=null}if(f&&"undefined"!=typeof f.HTMLIFrameElement&&(!a||!(a instanceof f.HTMLIFrameElement)&&(a instanceof f.Location||a instanceof f.Element))){if(w(a))try{var g=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(k){g="<object could not be stringified>"}else g=void 0===a?"undefined":null===a?"null":typeof a;D("Argument is not a %s (or a non-Element, non-Location mock); got: %s","HTMLIFrameElement",
g)}a.src=c.ld?c.ld:Xa(c).toString()};var Pb={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},Qb={"'":"\\'"},Rb=function(a){a=String(a);for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=c+1,g;if(!(g=Pb[d])){if(!(31<e&&127>e))if(d in Qb)d=Qb[d];else if(d in Pb)d=Qb[d]=Pb[d];else{g=d.charCodeAt(0);if(31<g&&127>g)e=d;else{if(256>g){if(e="\\x",16>g||256<g)e+="0"}else e="\\u",4096>g&&(e+="0");e+=g.toString(16).toUpperCase()}d=Qb[d]=e}g=d}b[f]=g}b.push('"');
return b.join("")},Sb=function(a){isFinite(a)&&(a=String(a));return r(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};var Tb=function(a,b){this.ec=a.name||null;this.Hc=a.be;this.$={};for(a=0;a<b.length;a++){var c=b[a];this.$[c.X]=c}};Tb.prototype.getName=function(){return this.ec};Tb.prototype.xa=function(){return this.Hc?this.Hc.w():null};var Ub=function(a){a=Ma(a.$);Ja(a,function(b,c){return b.X-c.X});return a};var Vb=function(a,b,c){this.u=a;C(!/[^0-9]/.test(b));this.X=b;this.ec=c.name;this.bc=!!c.ee;this.ea=c.Wb;this.fc=c.type};Vb.prototype.xa=function(){return this.u.prototype.w()};Vb.prototype.getName=function(){return this.ec};var Wb=function(){this.I={};this.$=this.w().$;this.J=this.Xc=null},Xb=function(a,b,c){c=c||a;for(var d in a.I){var e=Number(d);a.$[e]||b.call(c,e,a.I[d])}};h=Wb.prototype;h.has=function(a){C(a.xa()==this.w(),"The current message does not contain the given field");return null!=this.I[a.X]};
h.get=function(a,b){C(a.xa()==this.w(),"The current message does not contain the given field");var c=a.X;a=Yb(this,c);this.$[c].bc?(b=b||0,C(0<=b&&b<a.length,"Given index %s is out of bounds.  Repeated field length: %s",b,a.length),b=a[b]):b=a;return b};h.set=function(a,b){C(a.xa()==this.w(),"The current message does not contain the given field");I(this,a.X,b)};h.add=function(a,b){C(a.xa()==this.w(),"The current message does not contain the given field");Zb(this,a.X,b)};
h.clear=function(a){C(a.xa()==this.w(),"The current message does not contain the given field");a=a.X;delete this.I[a];this.J&&delete this.J[a]};
var $b=function(a,b){C(a.constructor==b.constructor,"The source message must have the same type.");for(var c=Ub(a.w()),d=0;d<c.length;d++){var e=c[d],f=e.X;if(null!=b.I[f]){a.J&&delete a.J[e.X];var g=11==e.ea||10==e.ea;if(e.bc){e=Yb(b,f)||[];for(var k=0;k<e.length;k++)Zb(a,f,g?e[k].clone():e[k])}else e=Yb(b,f),g?(g=Yb(a,f))?$b(g,e):I(a,f,e.clone()):I(a,f,e)}}};
Wb.prototype.clone=function(){var a=new this.constructor;C(a.constructor==this.constructor,"The source message must have the same type.");a!=this&&(a.I={},a.J&&(a.J={}),$b(a,this));return a};
var Yb=function(a,b){var c=a.I[b];return null==c?null:a.Xc?b in a.J?a.J[b]:(c=a.Xc.ce(a,a.$[b],c),a.J[b]=c):c},I=function(a,b,c){var d=a.$[b];14==d.ea?xa(c):C(Object(c).constructor==d.fc);a.I[b]=c;a.J&&(a.J[b]=c)},Zb=function(a,b,c){var d=a.$[b];14==d.ea?xa(c):C(Object(c).constructor==d.fc);a.I[b]||(a.I[b]=[]);a.I[b].push(c);a.J&&delete a.J[b]},ac=function(a,b){var c=[],d=b[0],e;for(e in b)0!=e&&c.push(new Vb(a,e,b[e]));return new Tb(d,c)};var J=function(){Wb.call(this)};y(J,Wb);var bc=null,cc=function(){Wb.call(this)};y(cc,Wb);var dc=null;J.prototype.w=function(){var a=bc;a||(bc=a=ac(J,{0:{name:"Version",Fd:"buzz.channel.Version"},1:{name:"major_version",Wb:5,type:Number},2:{name:"minor_version",Wb:5,type:Number}}));return a};J.w=J.prototype.w;cc.prototype.w=function(){var a=dc;a||(dc=a=ac(cc,{0:{name:"ProtocolVersion",Fd:"buzz.channel.ProtocolVersion"},1:{name:"version",Wb:11,type:J}}));return a};cc.w=cc.prototype.w;/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var ec="StopIteration"in p?p.StopIteration:{message:"StopIteration",stack:""},fc=function(){};fc.prototype.next=function(){throw ec;};fc.prototype.Nb=function(){return this};var gc=function(a,b){this.o={};this.h=[];this.jb=this.l=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};h=gc.prototype;h.O=function(){hc(this);for(var a=[],b=0;b<this.h.length;b++)a.push(this.o[this.h[b]]);return a};h.fa=function(){hc(this);return this.h.concat()};h.Ia=function(a){return ic(this.o,a)};h.clear=function(){this.o={};this.jb=this.l=this.h.length=0};
h.remove=function(a){return ic(this.o,a)?(delete this.o[a],this.l--,this.jb++,this.h.length>2*this.l&&hc(this),!0):!1};var hc=function(a){if(a.l!=a.h.length){for(var b=0,c=0;b<a.h.length;){var d=a.h[b];ic(a.o,d)&&(a.h[c++]=d);b++}a.h.length=c}if(a.l!=a.h.length){var e={};for(c=b=0;b<a.h.length;)d=a.h[b],ic(e,d)||(a.h[c++]=d,e[d]=1),b++;a.h.length=c}};h=gc.prototype;h.get=function(a,b){return ic(this.o,a)?this.o[a]:b};
h.set=function(a,b){ic(this.o,a)||(this.l++,this.h.push(a),this.jb++);this.o[a]=b};h.addAll=function(a){if(a instanceof gc)for(var b=a.fa(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};h.forEach=function(a,b){for(var c=this.fa(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new gc(this)};
h.Nb=function(a){hc(this);var b=0,c=this.jb,d=this,e=new fc;e.next=function(){if(c!=d.jb)throw Error("The map has changed since the iterator was created");if(b>=d.h.length)throw ec;var f=d.h[b++];return a?f:d.o[f]};return e};var ic=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var jc=function(a){if(a.O&&"function"==typeof a.O)return a.O();if(r(a))return a.split("");if(ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ma(a)},kc=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(ma(a)||r(a))Aa(a,b,c);else{if(a.fa&&"function"==typeof a.fa)var d=a.fa();else if(a.O&&"function"==typeof a.O)d=void 0;else if(ma(a)||r(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;e=jc(a);f=e.length;for(var g=
0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};var lc=function(a){this.o=new gc;a&&this.addAll(a)},mc=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+pa(a):b.substr(0,1)+a};h=lc.prototype;h.add=function(a){this.o.set(mc(a),a)};h.addAll=function(a){a=jc(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};h.cb=function(a){a=jc(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};h.remove=function(a){return this.o.remove(mc(a))};h.clear=function(){this.o.clear()};h.contains=function(a){return this.o.Ia(mc(a))};h.O=function(){return this.o.O()};
h.clone=function(){return new lc(this)};h.Nb=function(){return this.o.Nb(!1)};new lc([1,2,3]);new lc([1,2]);var nc=function(a){nc[" "](a);return a};nc[" "]=ka;var oc=function(a,b){try{return nc(a[b]),!0}catch(c){}return!1},qc=function(a,b){var c=pc;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var rc=H("Opera"),K=H("Trident")||H("MSIE"),sc=H("Edge"),tc=H("Gecko")&&!(-1!=G.toLowerCase().indexOf("webkit")&&!H("Edge"))&&!(H("Trident")||H("MSIE"))&&!H("Edge"),uc=-1!=G.toLowerCase().indexOf("webkit")&&!H("Edge"),vc=H("Macintosh"),wc=H("Windows"),xc=H("Android"),yc=H("iPhone")&&!H("iPod")&&!H("iPad"),zc=H("iPad"),Ac=H("iPod"),Bc=function(){var a=p.document;return a?a.documentMode:void 0},Cc;
a:{var Dc="",Ec=function(){var a=G;if(tc)return/rv:([^\);]+)(\)|;)/.exec(a);if(sc)return/Edge\/([\d\.]+)/.exec(a);if(K)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(uc)return/WebKit\/(\S+)/.exec(a);if(rc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ec&&(Dc=Ec?Ec[1]:"");if(K){var Fc=Bc();if(null!=Fc&&Fc>parseFloat(Dc)){Cc=String(Fc);break a}}Cc=Dc}
var Gc=Cc,pc={},Hc=function(a){return qc(a,function(){for(var b=0,c=Ya(String(Gc)).split("."),d=Ya(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==g[0].length&&0==k[0].length)break;b=gb(0==g[1].length?0:parseInt(g[1],10),0==k[1].length?0:parseInt(k[1],10))||gb(0==g[2].length,0==k[2].length)||gb(g[2],k[2]);g=g[3];k=k[3]}while(0==b)}return 0<=b})},Ic;
Ic=p.document&&K?Bc():void 0;var Jc=Object.freeze||function(a){return a};var Kc=function(){this.name="FINEST";this.value=300};Kc.prototype.toString=function(){return this.name};var Lc=new Kc;var Mc=function(){this.ed=ta()},Nc=null;Mc.prototype.set=function(a){this.ed=a};Mc.prototype.reset=function(){this.set(ta())};Mc.prototype.get=function(){return this.ed};var Oc=function(){Nc||(Nc=new Mc)},Pc=function(){Nc||(Nc=new Mc)};y(Pc,Oc);var L=function(){this.ma=this.ma;this.Aa=this.Aa};L.prototype.ma=!1;L.prototype.Sb=function(){this.ma||(this.ma=!0,this.g())};var Qc=function(a,b){a.ma?q(void 0)?b.call(void 0):b():(a.Aa||(a.Aa=[]),a.Aa.push(q(void 0)?x(b,void 0):b))};L.prototype.g=function(){if(this.Aa)for(;this.Aa.length;)this.Aa.shift()()};var Rc=function(a){a&&"function"==typeof a.Sb&&a.Sb()};var Sc=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Da=!1;this.hd=!0};Sc.prototype.stopPropagation=function(){this.Da=!0};Sc.prototype.preventDefault=function(){this.defaultPrevented=!0;this.hd=!1};var Tc;(Tc=!K)||(Tc=9<=Number(Ic));var Uc=Tc,Vc=K&&!Hc("9"),Wc=function(){if(!p.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{p.addEventListener("test",ka,b),p.removeEventListener("test",ka,b)}catch(c){}return a}();var Xc=function(a,b){Sc.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.na=null;a&&this.$b(a,b)};y(Xc,Sc);var Yc=Jc({2:"touch",3:"pen",4:"mouse"});
Xc.prototype.$b=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;(b=a.relatedTarget)?tc&&(oc(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.offsetX=uc||void 0!==a.offsetX?
a.offsetX:a.layerX,this.offsetY=uc||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=r(a.pointerType)?
a.pointerType:Yc[a.pointerType]||"";this.state=a.state;this.na=a;a.defaultPrevented&&this.preventDefault()};Xc.prototype.stopPropagation=function(){Xc.G.stopPropagation.call(this);this.na.stopPropagation?this.na.stopPropagation():this.na.cancelBubble=!0};Xc.prototype.preventDefault=function(){Xc.G.preventDefault.call(this);var a=this.na;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Vc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Zc="closure_listenable_"+(1E6*Math.random()|0),$c=function(a){return!(!a||!a[Zc])},ad=0;var bd=function(a,b,c,d,e){this.listener=a;this.Bb=null;this.src=b;this.type=c;this.capture=!!d;this.ya=e;this.key=++ad;this.Sa=this.nb=!1},cd=function(a){a.Sa=!0;a.listener=null;a.Bb=null;a.src=null;a.ya=null};var dd=function(a){this.src=a;this.A={};this.ib=0};dd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.A[f];a||(a=this.A[f]=[],this.ib++);var g=ed(a,b,d,e);-1<g?(b=a[g],c||(b.nb=!1)):(b=new bd(b,this.src,f,!!d,e),b.nb=c,a.push(b));return b};dd.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.A))return!1;var e=this.A[a];b=ed(e,b,c,d);return-1<b?(cd(e[b]),C(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.A[a],this.ib--),!0):!1};
var fd=function(a,b){var c=b.type;c in a.A&&Fa(a.A[c],b)&&(cd(b),0==a.A[c].length&&(delete a.A[c],a.ib--))};dd.prototype.cb=function(a){a=a&&a.toString();var b=0,c;for(c in this.A)if(!a||c==a){for(var d=this.A[c],e=0;e<d.length;e++)++b,cd(d[e]);delete this.A[c];this.ib--}};dd.prototype.Va=function(a,b,c,d){a=this.A[a.toString()];var e=-1;a&&(e=ed(a,b,c,d));return-1<e?a[e]:null};
dd.prototype.hasListener=function(a,b){var c=q(a),d=c?a.toString():"",e=q(b);return La(this.A,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};var ed=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Sa&&f.listener==b&&f.capture==!!c&&f.ya==d)return e}return-1};var gd="closure_lm_"+(1E6*Math.random()|0),hd={},id=0,kd=function(a,b,c,d,e){if(d&&d.once)return jd(a,b,c,d,e);if(u(b)){for(var f=0;f<b.length;f++)kd(a,b[f],c,d,e);return null}c=ld(c);return $c(a)?a.Za(b,c,w(d)?!!d.capture:!!d,e):md(a,b,c,!1,d,e)},md=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=w(e)?!!e.capture:!!e,k=nd(a);k||(a[gd]=k=new dd(a));c=k.add(b,c,d,g,f);if(c.Bb)return c;d=od();c.Bb=d;d.src=a;d.listener=c;if(a.addEventListener)Wc||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent(pd(b.toString()),d);else if(a.addListener&&a.removeListener)C("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");id++;return c},od=function(){var a=qd,b=Uc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},jd=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)jd(a,b[f],c,d,e);return null}c=ld(c);return $c(a)?
a.cc(b,c,w(d)?!!d.capture:!!d,e):md(a,b,c,!0,d,e)},rd=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)rd(a,b[f],c,d,e);else d=w(d)?!!d.capture:!!d,c=ld(c),$c(a)?a.uc(b,c,d,e):a&&(a=nd(a))&&(b=a.Va(b,c,d,e))&&sd(b)},sd=function(a){if(!ha(a)&&a&&!a.Sa){var b=a.src;if($c(b))fd(b.S,a);else{var c=a.type,d=a.Bb;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(pd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);id--;(c=nd(b))?(fd(c,a),0==c.ib&&(c.src=
null,b[gd]=null)):cd(a)}}},td=function(a,b,c,d,e){c=ld(c);d=!!d;return $c(a)?a.Va(b,c,d,e):a?(a=nd(a))?a.Va(b,c,d,e):null:null},pd=function(a){return a in hd?hd[a]:hd[a]="on"+a},vd=function(a,b,c,d){var e=!0;if(a=nd(a))if(b=a.A[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.Sa&&(f=ud(f,d),e=e&&!1!==f)}return e},ud=function(a,b){var c=a.listener,d=a.ya||a.src;a.nb&&sd(a);return c.call(d,b)},qd=function(a,b){if(a.Sa)return!0;if(!Uc){var c=b||ja("window.event");b=new Xc(c,
this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.currentTarget;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.Da&&0<=e;e--){b.currentTarget=c[e];var f=vd(c[e],a,!0,b);d=d&&f}for(e=0;!b.Da&&e<c.length;e++)b.currentTarget=c[e],f=vd(c[e],a,!1,b),d=d&&f}return d}return ud(a,new Xc(b,this))},nd=function(a){a=a[gd];return a instanceof dd?a:null},wd="__closure_events_fn_"+
(1E9*Math.random()>>>0),ld=function(a){C(a,"Listener can not be null.");if(v(a))return a;C(a.handleEvent,"An object listener must have handleEvent method.");a[wd]||(a[wd]=function(b){return a.handleEvent(b)});return a[wd]};var M=function(){L.call(this);this.S=new dd(this);this.sd=this;this.ic=null};y(M,L);M.prototype[Zc]=!0;h=M.prototype;h.addEventListener=function(a,b,c,d){kd(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){rd(this,a,b,c,d)};
h.dispatchEvent=function(a){xd(this);var b=this.ic;if(b){var c=[];for(var d=1;b;b=b.ic)c.push(b),C(1E3>++d,"infinite loop")}b=this.sd;d=a.type||a;if(r(a))a=new Sc(a,b);else if(a instanceof Sc)a.target=a.target||b;else{var e=a;a=new Sc(d,b);Oa(a,e)}e=!0;if(c)for(var f=c.length-1;!a.Da&&0<=f;f--){var g=a.currentTarget=c[f];e=yd(g,d,!0,a)&&e}a.Da||(g=a.currentTarget=b,e=yd(g,d,!0,a)&&e,a.Da||(e=yd(g,d,!1,a)&&e));if(c)for(f=0;!a.Da&&f<c.length;f++)g=a.currentTarget=c[f],e=yd(g,d,!1,a)&&e;return e};
h.g=function(){M.G.g.call(this);this.S&&this.S.cb(void 0);this.ic=null};h.Za=function(a,b,c,d){xd(this);return this.S.add(String(a),b,!1,c,d)};h.cc=function(a,b,c,d){return this.S.add(String(a),b,!0,c,d)};h.uc=function(a,b,c,d){this.S.remove(String(a),b,c,d)};var yd=function(a,b,c,d){b=a.S.A[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.Sa&&g.capture==c){var k=g.listener,l=g.ya||g.src;g.nb&&fd(a.S,g);e=!1!==k.call(l,d)&&e}}return e&&0!=d.hd};
M.prototype.Va=function(a,b,c,d){return this.S.Va(String(a),b,c,d)};M.prototype.hasListener=function(a,b){return this.S.hasListener(q(a)?String(a):void 0,b)};var xd=function(a){C(a.S,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var zd=function(){this.Cb=void 0};zd.prototype.Fb=function(a){var b=[];Ad(this,a,b);return b.join("")};
var Ad=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(u(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],Ad(a,a.Cb?a.Cb.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),Bd(d,c),c.push(":"),Ad(a,a.Cb?a.Cb.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":Bd(b,
c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}},Cd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Dd=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g,Bd=function(a,b){b.push('"',a.replace(Dd,function(c){var d=Cd[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),
Cd[c]=d);return d}),'"')};var Ed=function(a){var b=N.c;b&&b.log(Lc,a,void 0)},O=function(a,b){a&&a.fe(b,void 0)},P=function(a){var b=N.c;b&&b.info(a,void 0)},Q=function(a,b){a&&a.de(b,void 0)};var Fd=function(a,b){this.Kd=100;this.yd=a;this.Qd=b;this.vb=0;this.sb=null};Fd.prototype.get=function(){if(0<this.vb){this.vb--;var a=this.sb;this.sb=a.next;a.next=null}else a=this.yd();return a};Fd.prototype.put=function(a){this.Qd(a);this.vb<this.Kd&&(this.vb++,a.next=this.sb,this.sb=a)};var Gd=function(a){p.setTimeout(function(){throw a;},0)},Hd,Id=function(){var a=p.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!H("Presto")&&(a=function(){var e=document.createElement("IFRAME");e.style.display="none";Ob(e);document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.write(Eb(Jb));e.close();var g="callImmediate"+Math.random(),k="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;
e=x(function(l){if(("*"==k||l.origin==k)&&l.data==g)this.port1.onmessage()},this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,k)}}});if("undefined"!==typeof a&&!H("Trident")&&!H("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(q(c.next)){c=c.next;var e=c.Gc;c.Gc=null;e()}};return function(e){d.next={Gc:e};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?
function(e){var f=document.createElement("SCRIPT");f.onreadystatechange=function(){f.onreadystatechange=null;f.parentNode.removeChild(f);f=null;e();e=null};document.documentElement.appendChild(f)}:function(e){p.setTimeout(e,0)}};var Jd=function(){this.Kb=this.Fa=null},Ld=new Fd(function(){return new Kd},function(a){a.reset()});Jd.prototype.add=function(a,b){var c=Ld.get();c.set(a,b);this.Kb?this.Kb.next=c:(C(!this.Fa),this.Fa=c);this.Kb=c};Jd.prototype.remove=function(){var a=null;this.Fa&&(a=this.Fa,this.Fa=this.Fa.next,this.Fa||(this.Kb=null),a.next=null);return a};var Kd=function(){this.next=this.scope=this.Xb=null};Kd.prototype.set=function(a,b){this.Xb=a;this.scope=b;this.next=null};
Kd.prototype.reset=function(){this.next=this.scope=this.Xb=null};var Qd=function(a,b){Md||Nd();Od||(Md(),Od=!0);Pd.add(a,b)},Md,Nd=function(){if(p.Promise&&p.Promise.resolve){var a=p.Promise.resolve(void 0);Md=function(){a.then(Rd)}}else Md=function(){var b=Rd;!v(p.setImmediate)||p.Window&&p.Window.prototype&&!H("Edge")&&p.Window.prototype.setImmediate==p.setImmediate?(Hd||(Hd=Id()),Hd(b)):p.setImmediate(b)}},Od=!1,Pd=new Jd,Rd=function(){for(var a;a=Pd.remove();){try{a.Xb.call(a.scope)}catch(b){Gd(b)}Ld.put(a)}Od=!1};var Sd=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var Vd=function(a){this.f=0;this.L=void 0;this.Ha=this.ca=this.u=null;this.rb=this.Vb=!1;if(a!=ka)try{var b=this;a.call(void 0,function(c){Td(b,2,c)},function(c){if(!(c instanceof Ud))try{if(c instanceof Error)throw c;throw Error("Promise rejected.");}catch(d){}Td(b,3,c)})}catch(c){Td(this,3,c)}},Wd=function(){this.next=this.context=this.Pa=this.Ba=this.ua=null;this.kb=!1};Wd.prototype.reset=function(){this.context=this.Pa=this.Ba=this.ua=null;this.kb=!1};
var Xd=new Fd(function(){return new Wd},function(a){a.reset()}),Yd=function(a,b,c){var d=Xd.get();d.Ba=a;d.Pa=b;d.context=c;return d};Vd.prototype.then=function(a,b,c){null!=a&&ya(a,"opt_onFulfilled should be a function.");null!=b&&ya(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return Zd(this,v(a)?a:null,v(b)?b:null,c)};Vd.prototype.$goog_Thenable=!0;
Vd.prototype.cancel=function(a){0==this.f&&Qd(function(){var b=new Ud(a);$d(this,b)},this)};
var $d=function(a,b){if(0==a.f)if(a.u){var c=a.u;if(c.ca){for(var d=0,e=null,f=null,g=c.ca;g&&(g.kb||(d++,g.ua==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.f&&1==d?$d(c,b):(f?(d=f,C(c.ca),C(null!=d),d.next==c.Ha&&(c.Ha=d),d.next=d.next.next):ae(c),be(c,e,3,b)))}a.u=null}else Td(a,3,b)},de=function(a,b){a.ca||2!=a.f&&3!=a.f||ce(a);C(null!=b.Ba);a.Ha?a.Ha.next=b:a.ca=b;a.Ha=b},Zd=function(a,b,c,d){var e=Yd(null,null,null);e.ua=new Vd(function(f,g){e.Ba=b?function(k){try{var l=b.call(d,k);f(l)}catch(m){g(m)}}:
f;e.Pa=c?function(k){try{var l=c.call(d,k);!q(l)&&k instanceof Ud?g(k):f(l)}catch(m){g(m)}}:g});e.ua.u=a;de(a,e);return e.ua};Vd.prototype.Zd=function(a){C(1==this.f);this.f=0;Td(this,2,a)};Vd.prototype.$d=function(a){C(1==this.f);this.f=0;Td(this,3,a)};
var Td=function(a,b,c){if(0==a.f){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.f=1;a:{var d=c,e=a.Zd,f=a.$d;if(d instanceof Vd){null!=e&&ya(e,"opt_onFulfilled should be a function.");null!=f&&ya(f,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");de(d,Yd(e||ka,f||null,a));var g=!0}else if(Sd(d))d.then(e,f,a),g=!0;else{if(w(d))try{var k=d.then;if(v(k)){ee(d,k,e,f,a);g=!0;break a}}catch(l){f.call(a,l);g=!0;break a}g=!1}}g||
(a.L=c,a.f=b,a.u=null,ce(a),3!=b||c instanceof Ud||fe(a,c))}},ee=function(a,b,c,d,e){var f=!1,g=function(l){f||(f=!0,c.call(e,l))},k=function(l){f||(f=!0,d.call(e,l))};try{b.call(a,g,k)}catch(l){k(l)}},ce=function(a){a.Vb||(a.Vb=!0,Qd(a.Dd,a))},ae=function(a){var b=null;a.ca&&(b=a.ca,a.ca=b.next,b.next=null);a.ca||(a.Ha=null);null!=b&&C(null!=b.Ba);return b};Vd.prototype.Dd=function(){for(var a;a=ae(this);)be(this,a,this.f,this.L);this.Vb=!1};
var be=function(a,b,c,d){if(3==c&&b.Pa&&!b.kb)for(;a&&a.rb;a=a.u)a.rb=!1;if(b.ua)b.ua.u=null,ge(b,c,d);else try{b.kb?b.Ba.call(b.context):ge(b,c,d)}catch(e){he.call(null,e)}Xd.put(b)},ge=function(a,b,c){2==b?a.Ba.call(a.context,c):a.Pa&&a.Pa.call(a.context,c)},fe=function(a,b){a.rb=!0;Qd(function(){a.rb&&he.call(null,b)})},he=Gd,Ud=function(a){z.call(this,a)};y(Ud,z);Ud.prototype.name="cancel";var ie=function(a,b){M.call(this);this.Na=a||1;this.hb=b||p;this.Ec=x(this.Yd,this);this.Wc=ta()};y(ie,M);h=ie.prototype;h.enabled=!1;h.Y=null;h.setInterval=function(a){this.Na=a;this.Y&&this.enabled?(this.stop(),this.start()):this.Y&&this.stop()};h.Yd=function(){if(this.enabled){var a=ta()-this.Wc;0<a&&a<.8*this.Na?this.Y=this.hb.setTimeout(this.Ec,this.Na-a):(this.Y&&(this.hb.clearTimeout(this.Y),this.Y=null),this.dispatchEvent("tick"),this.enabled&&(this.stop(),this.start()))}};
h.start=function(){this.enabled=!0;this.Y||(this.Y=this.hb.setTimeout(this.Ec,this.Na),this.Wc=ta())};h.stop=function(){this.enabled=!1;this.Y&&(this.hb.clearTimeout(this.Y),this.Y=null)};h.g=function(){ie.G.g.call(this);this.stop();delete this.hb};var je=function(a,b,c){if(v(a))c&&(a=x(a,c));else if(a&&"function"==typeof a.handleEvent)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:p.setTimeout(a,b||0)};var R=function(a){L.call(this);this.La=a;this.h={}};y(R,L);var ke=[];R.prototype.Za=function(a,b,c,d){u(b)||(b&&(ke[0]=b.toString()),b=ke);for(var e=0;e<b.length;e++){var f=kd(a,b[e],c||this.handleEvent,d||!1,this.La||this);if(!f)break;this.h[f.key]=f}return this};R.prototype.cc=function(a,b,c,d){return le(this,a,b,c,d)};var le=function(a,b,c,d,e,f){if(u(c))for(var g=0;g<c.length;g++)le(a,b,c[g],d,e,f);else{b=jd(b,c,d||a.handleEvent,e,f||a.La||a);if(!b)return a;a.h[b.key]=b}return a};
R.prototype.uc=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.uc(a,b[f],c,d,e);else if(a=td(a,b,c||this.handleEvent,w(d)?!!d.capture:!!d,e||this.La||this))sd(a),delete this.h[a.key]};R.prototype.cb=function(){Ka(this.h,function(a,b){this.h.hasOwnProperty(b)&&sd(a)},this);this.h={}};R.prototype.g=function(){R.G.g.call(this);this.cb()};R.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var me=function(){};me.prototype.Fc=null;var oe=function(a){var b;(b=a.Fc)||(b={},ne(a)&&(b[0]=!0,b[1]=!0),b=a.Fc=b);return b};var pe,qe=function(){};y(qe,me);var re=function(a){return(a=ne(a))?new ActiveXObject(a):new XMLHttpRequest},ne=function(a){if(!a.Tc&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.Tc=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.Tc};pe=new qe;var se=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,te=function(a){var b=a.match(se);a=b[1];var c=b[2],d=b[3];b=b[4];var e="";a&&(e+=a+":");d&&(e+="//",c&&(e+=c+"@"),e+=d,b&&(e+=":"+b));return e},ue=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var S=function(a){this.da=this.Ea=this.sa="";this.Ra=null;this.wa=this.ba="";this.P=this.Jd=!1;if(a instanceof S){this.P=q(void 0)?void 0:a.P;ve(this,a.sa);var b=a.Ea;T(this);this.Ea=b;b=a.da;T(this);this.da=b;we(this,a.Ra);b=a.ba;T(this);this.ba=b;xe(this,a.B.clone());a=a.wa;T(this);this.wa=a}else a&&(b=String(a).match(se))?(this.P=!1,ve(this,b[1]||"",!0),a=b[2]||"",T(this),this.Ea=ye(a),a=b[3]||"",T(this),this.da=ye(a,!0),we(this,b[4]),a=b[5]||"",T(this),this.ba=ye(a,!0),xe(this,b[6]||"",!0),a=
b[7]||"",T(this),this.wa=ye(a)):(this.P=!1,this.B=new ze(null,this.P))};
S.prototype.toString=function(){var a=[],b=this.sa;b&&a.push(Ae(b,Be,!0),":");var c=this.da;if(c||"file"==b)a.push("//"),(b=this.Ea)&&a.push(Ae(b,Be,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Ra,null!=c&&a.push(":",String(c));if(c=this.ba)this.da&&"/"!=c.charAt(0)&&a.push("/"),a.push(Ae(c,"/"==c.charAt(0)?Ce:De,!0));(c=this.B.toString())&&a.push("?",c);(c=this.wa)&&a.push("#",Ae(c,Ee));return a.join("")};
S.prototype.resolve=function(a){var b=this.clone(),c=!!a.sa;c?ve(b,a.sa):c=!!a.Ea;if(c){var d=a.Ea;T(b);b.Ea=d}else c=!!a.da;c?(d=a.da,T(b),b.da=d):c=null!=a.Ra;d=a.ba;if(c)we(b,a.Ra);else if(c=!!a.ba){if("/"!=d.charAt(0))if(this.da&&!this.ba)d="/"+d;else{var e=b.ba.lastIndexOf("/");-1!=e&&(d=b.ba.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var k=e[g++];"."==k?d&&g==e.length&&
f.push(""):".."==k?((1<f.length||1==f.length&&""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?(T(b),b.ba=d):c=""!==a.B.toString();c?xe(b,a.B.clone()):c=!!a.wa;c&&(a=a.wa,T(b),b.wa=a);return b};S.prototype.clone=function(){return new S(this)};
var ve=function(a,b,c){T(a);a.sa=c?ye(b,!0):b;a.sa&&(a.sa=a.sa.replace(/:$/,""))},we=function(a,b){T(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.Ra=b}else a.Ra=null},xe=function(a,b,c){T(a);b instanceof ze?(a.B=b,a.B.rc(a.P)):(c||(b=Ae(b,Fe)),a.B=new ze(b,a.P))};S.prototype.getQuery=function(){return this.B.toString()};S.prototype.removeParameter=function(a){T(this);this.B.remove(a);return this};
var T=function(a){if(a.Jd)throw Error("Tried to modify a read-only Uri");};S.prototype.rc=function(a){this.P=a;this.B&&this.B.rc(a)};
var ye=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Ae=function(a,b,c){return r(a)?(a=encodeURI(a).replace(b,Ge),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Ge=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Be=/[#\/\?@]/g,De=/[#\?:]/g,Ce=/[#\?]/g,Fe=/[#\?@]/g,Ee=/#/g,ze=function(a,b){this.l=this.j=null;this.K=a||null;this.P=!!b},He=function(a){a.j||(a.j=new gc,a.l=0,a.K&&ue(a.K,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,
" ")),c)}))};h=ze.prototype;h.add=function(a,b){He(this);this.K=null;a=Ie(this,a);var c=this.j.get(a);c||this.j.set(a,c=[]);c.push(b);this.l=xa(this.l)+1;return this};h.remove=function(a){He(this);a=Ie(this,a);return this.j.Ia(a)?(this.K=null,this.l=xa(this.l)-this.j.get(a).length,this.j.remove(a)):!1};h.clear=function(){this.j=this.K=null;this.l=0};h.Ia=function(a){He(this);a=Ie(this,a);return this.j.Ia(a)};
h.forEach=function(a,b){He(this);this.j.forEach(function(c,d){Aa(c,function(e){a.call(b,e,d,this)},this)},this)};h.fa=function(){He(this);for(var a=this.j.O(),b=this.j.fa(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};h.O=function(a){He(this);var b=[];if(r(a))this.Ia(a)&&(b=Ga(b,this.j.get(Ie(this,a))));else{a=this.j.O();for(var c=0;c<a.length;c++)b=Ga(b,a[c])}return b};
h.set=function(a,b){He(this);this.K=null;a=Ie(this,a);this.Ia(a)&&(this.l=xa(this.l)-this.j.get(a).length);this.j.set(a,[b]);this.l=xa(this.l)+1;return this};h.get=function(a,b){if(!a)return b;a=this.O(a);return 0<a.length?String(a[0]):b};
h.toString=function(){if(this.K)return this.K;if(!this.j)return"";for(var a=[],b=this.j.fa(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.O(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.K=a.join("&")};h.clone=function(){var a=new ze;a.K=this.K;this.j&&(a.j=this.j.clone(),a.l=this.l);return a};var Ie=function(a,b){b=String(b);a.P&&(b=b.toLowerCase());return b};
ze.prototype.rc=function(a){a&&!this.P&&(He(this),this.K=null,this.j.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<b.length&&(this.K=null,this.j.set(Ie(this,d),Ha(b)),this.l=xa(this.l)+b.length))},this));this.P=a};ze.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)kc(arguments[b],function(c,d){this.add(d,c)},this)};var U=function(a){M.call(this);this.headers=new gc;this.Mb=a||null;this.ja=!1;this.Lb=this.b=null;this.Ya=this.Vc=this.ub="";this.za=this.Zb=this.tb=this.Ub=!1;this.gb=0;this.Gb=null;this.gd="";this.Jb=this.Pd=this.vc=!1};y(U,M);var Je=/^https?$/i,Ke=["POST","PUT"],Le=[];U.prototype.wd=function(){this.Sb();Fa(Le,this)};
U.prototype.send=function(a,b,c,d){if(this.b)throw Error("[goog.net.XhrIo] Object is active with another request="+this.ub+"; newUri="+a);b=b?b.toUpperCase():"GET";this.ub=a;this.Ya="";this.Vc=b;this.Ub=!1;this.ja=!0;this.b=this.Mb?re(this.Mb):re(pe);this.Lb=this.Mb?oe(this.Mb):oe(pe);this.b.onreadystatechange=x(this.ad,this);this.Pd&&"onprogress"in this.b&&(this.b.onprogress=x(function(f){this.$c(f,!0)},this),this.b.upload&&(this.b.upload.onprogress=x(this.$c,this)));try{Q(this.V,Me(this,"Opening Xhr")),
this.Zb=!0,this.b.open(b,String(a),!0),this.Zb=!1}catch(f){Q(this.V,Me(this,"Error opening Xhr: "+f.message));this.qb(5,f);return}a=c||"";var e=this.headers.clone();d&&kc(d,function(f,g){e.set(g,f)});d=Ea(e.fa());c=p.FormData&&a instanceof p.FormData;!(0<=za(Ke,b))||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,g){this.b.setRequestHeader(g,f)},this);this.gd&&(this.b.responseType=this.gd);"withCredentials"in this.b&&this.b.withCredentials!==this.vc&&
(this.b.withCredentials=this.vc);try{Ne(this),0<this.gb&&(this.Jb=Oe(this.b),Q(this.V,Me(this,"Will abort after "+this.gb+"ms if incomplete, xhr2 "+this.Jb)),this.Jb?(this.b.timeout=this.gb,this.b.ontimeout=x(this.kd,this)):this.Gb=je(this.kd,this.gb,this)),Q(this.V,Me(this,"Sending request")),this.tb=!0,this.b.send(a),this.tb=!1}catch(f){Q(this.V,Me(this,"Send error: "+f.message)),this.qb(5,f)}};
var Oe=function(a){return K&&Hc(9)&&ha(a.timeout)&&q(a.ontimeout)},Da=function(a){return"content-type"==a.toLowerCase()};U.prototype.kd=function(){"undefined"!=typeof fa&&this.b&&(this.Ya="Timed out after "+this.gb+"ms, aborting",Q(this.V,Me(this,this.Ya)),this.dispatchEvent("timeout"),this.abort(8))};U.prototype.qb=function(a,b){this.ja=!1;this.b&&(this.za=!0,this.b.abort(),this.za=!1);this.Ya=b;Pe(this);Qe(this)};var Pe=function(a){a.Ub||(a.Ub=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};
U.prototype.abort=function(){this.b&&this.ja&&(Q(this.V,Me(this,"Aborting")),this.ja=!1,this.za=!0,this.b.abort(),this.za=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Qe(this))};U.prototype.g=function(){this.b&&(this.ja&&(this.ja=!1,this.za=!0,this.b.abort(),this.za=!1),Qe(this,!0));U.G.g.call(this)};U.prototype.ad=function(){this.ma||(this.Zb||this.tb||this.za?Re(this):this.Md())};U.prototype.Md=function(){Re(this)};
var Re=function(a){if(a.ja&&"undefined"!=typeof fa)if(a.Lb[1]&&4==Se(a)&&2==Te(a))Q(a.V,Me(a,"Local request error detected and ignored"));else if(a.tb&&4==Se(a))je(a.ad,0,a);else if(a.dispatchEvent("readystatechange"),4==Se(a)){Q(a.V,Me(a,"Request complete"));a.ja=!1;try{if(Ue(a))a.dispatchEvent("complete"),a.dispatchEvent("success");else{try{var b=2<Se(a)?a.b.statusText:""}catch(c){Q(a.V,"Can not get status: "+c.message),b=""}a.Ya=b+" ["+Te(a)+"]";Pe(a)}}finally{Qe(a)}}};
U.prototype.$c=function(a,b){C("progress"===a.type,"goog.net.EventType.PROGRESS is of the same type as raw XHR progress.");this.dispatchEvent(Ve(a,"progress"));this.dispatchEvent(Ve(a,b?"downloadprogress":"uploadprogress"))};
var Ve=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}},Qe=function(a,b){if(a.b){Ne(a);var c=a.b,d=a.Lb[0]?ka:null;a.b=null;a.Lb=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){O(a.V,"Problem encountered resetting onreadystatechange: "+e.message)}}},Ne=function(a){a.b&&a.Jb&&(a.b.ontimeout=null);a.Gb&&(p.clearTimeout(a.Gb),a.Gb=null)};U.prototype.ac=function(){return!!this.b};
var Ue=function(a){var b=Te(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.ub).match(se)[1]||null,!a&&p.self&&p.self.location&&(a=p.self.location.protocol,a=a.substr(0,a.length-1)),b=!Je.test(a?a.toLowerCase():"");c=b}return c},Se=function(a){return a.b?a.b.readyState:0},Te=function(a){try{return 2<Se(a)?a.b.status:-1}catch(b){return-1}},We=function(a){try{return a.b?a.b.responseText:""}catch(b){return Q(a.V,
"Can not get responseText: "+b.message),""}};U.prototype.getResponseHeader=function(a){if(this.b&&4==Se(this))return a=this.b.getResponseHeader(a),null===a?void 0:a};U.prototype.getAllResponseHeaders=function(){return this.b&&4==Se(this)?this.b.getAllResponseHeaders()||"":""};var Me=function(a,b){return b+" ["+a.Vc+" "+a.ub+" "+Te(a)+"]"};new M;new Pc;var Ye=function(a,b,c){function d(g){g&&b.appendChild(r(g)?a.createTextNode(g):g)}for(var e=1;e<c.length;e++){var f=c[e];!ma(f)||w(f)&&0<f.nodeType?d(f):Aa(Xe(f)?Ha(f):f,d)}},Ze=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null},Xe=function(a){if(a&&"number"==typeof a.length){if(w(a))return"function"==typeof a.item||"string"==typeof a.item;if(v(a))return"function"==typeof a.item}return!1},$e=function(){this.Ua=p.document||document};h=$e.prototype;
h.getElementsByTagName=function(a,b){return(b||this.Ua).getElementsByTagName(String(a))};h.createElement=function(a){return this.Ua.createElement(String(a))};h.createTextNode=function(a){return this.Ua.createTextNode(String(a))};h.i=function(){var a=this.Ua;return a.parentWindow||a.defaultView};h.appendChild=function(a,b){C(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};
h.append=function(a,b){var c=a;C(c,"Node cannot be null or undefined.");Ye(9==c.nodeType?c:c.ownerDocument||c.document,a,arguments)};h.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
h.removeNode=Ze;h.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var af=function(){};var bf=function(a,b){this.md=!!b};y(bf,af);bf.prototype.Fb=function(a){var b=new cf;df(this,a,b);return b.toString()};
var df=function(a,b,c){var d=Ub(b.w());Aa(d,function(e){if(b.has(e)){C(e.xa()==b.w(),"The current message does not contain the given field");var f=e.X;f=b.$[f].bc?null!=b.I[f]?b.I[f].length:0:null!=b.I[f]?1:0;for(var g=0;g<f;++g){c.append(e.getName());11==e.ea||10==e.ea?(c.append(" {"),ef(c),c.oa+=2):c.append(": ");ff(this,b.get(e,g),e,c);if(11==e.ea||10==e.ea)gf(c),c.append("}");ef(c)}}},a);Xb(b,function(e,f){hf(this,e,f,C(c))},a)},hf=function(a,b,c,d){if(null!=c)if(u(c))Aa(c,function(g){hf(this,
b,g,d)},a);else{if(w(c)){d.append(b);d.append(" {");ef(d);d.oa+=2;if(c instanceof Wb)df(a,c,d);else for(var e in c){var f=Sb(e);C(isFinite(f)&&0==f%1);hf(a,f,c[e],d)}gf(d);d.append("}")}else r(c)&&(c=Rb(c)),d.append(b),d.append(": "),d.append(c.toString());ef(d)}},ff=function(a,b,c,d){switch(c.ea){case 1:case 2:case 3:case 4:case 5:case 13:case 6:case 7:case 8:case 15:case 16:case 17:case 18:d.append(b);break;case 12:case 9:b=Rb(b.toString());d.append(b);break;case 14:if(!a.md){var e=!1;Ka(c.fc,function(f,
g){e||f!=b||(d.append(g),e=!0)})}e&&!a.md||d.append(b.toString());break;case 10:case 11:df(a,b,d)}},cf=function(){this.oa=0;this.mb=[];this.oc=!0};cf.prototype.toString=function(){return this.mb.join("")};var gf=function(a){a.oa-=2;C(0<=a.oa)};cf.prototype.append=function(a){if(this.oc){for(var b=0;b<this.oa;++b)this.mb.push(" ");this.oc=!1}this.mb.push(a.toString())};var ef=function(a){a.mb.push("\n");a.oc=!0};var jf=new bf;Wb.prototype.toString=function(){return jf.Fb(this)};var kf=new cc,lf=new J;I(lf,1,3);I(lf,2,2);I(kf,1,lf);var mf=new J;I(mf,1,3);I(mf,2,2);var nf=new J;I(nf,1,3);I(nf,2,2);(function(){if(wc){var a=/Windows NT ([0-9.]+)/;return(a=a.exec(G))?a[1]:"0"}return vc?(a=/10[_.][0-9_.]+/,(a=a.exec(G))?a[0].replace(/_/g,"."):"10"):xc?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(G))?a[1]:""):yc||zc||Ac?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(G))?a[1].replace(/_/g,"."):""):""})();var of=function(a,b,c){L.call(this);this.dc=a;this.Na=b||0;this.La=c;this.vd=x(this.Bd,this)};y(of,L);h=of.prototype;h.U=0;h.g=function(){of.G.g.call(this);this.stop();delete this.dc;delete this.La};h.start=function(a){this.stop();this.U=je(this.vd,q(a)?a:this.Na)};h.stop=function(){this.ac()&&p.clearTimeout(this.U);this.U=0};h.ac=function(){return 0!=this.U};h.Bd=function(){this.U=0;this.dc&&this.dc.call(this.La)};var pf=function(){L.call(this);this.qc={}};y(pf,L);pf.prototype.connect=function(a){a&&a()};pf.prototype.isConnected=function(){return!0};pf.prototype.g=function(){pf.G.g.call(this);delete this.qc;delete this.Lc};var N={};var qf={1:"NativeMessagingTransport",2:"FrameElementMethodTransport",3:"IframeRelayTransport",4:"IframePollingTransport",5:"FlashTransport",6:"NixTransport",7:"DirectTransport"},rf=["pu","lru","pru","lpu","ppu"],V={},tf=function(){for(var a=10,b=sf,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},sf="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var W=function(a){L.call(this);this.Z=a||ua||(ua=new $e)};y(W,L);W.prototype.Ta=0;W.prototype.i=function(){return this.Z.i()};W.prototype.getName=function(){return qf[String(this.Ta)]||""};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var X=function(){this.Eb=[];this.Zc=void 0;this.Kc=null;this.Wa=this.N=!1;this.L=void 0;this.sc=this.Dc=this.Ob=!1;this.Ib=0;this.u=null;this.lb=0};X.prototype.cancel=function(a){if(this.N)this.L instanceof X&&this.L.cancel();else{if(this.u){var b=this.u;delete this.u;a?b.cancel(a):(b.lb--,0>=b.lb&&b.cancel())}this.Zc?this.Zc.call(this.Kc,this):this.sc=!0;this.N||this.Nc(new uf(this))}};X.prototype.Jc=function(a,b){this.Ob=!1;vf(this,a,b)};
var vf=function(a,b,c){a.N=!0;a.L=c;a.Wa=!b;wf(a)},yf=function(a){if(a.N){if(!a.sc)throw new xf(a);a.sc=!1}};X.prototype.M=function(a){yf(this);zf(a);vf(this,!0,a)};X.prototype.Nc=function(a){yf(this);zf(a);vf(this,!1,a)};var zf=function(a){C(!(a instanceof X),"An execution sequence may not be initiated with a blocking Deferred.")},Bf=function(a,b,c){Af(a,b,null,c)},Af=function(a,b,c,d){C(!a.Dc,"Blocking Deferreds can not be re-used");a.Eb.push([b,c,d]);a.N&&wf(a)};
X.prototype.then=function(a,b,c){var d,e,f=new Vd(function(g,k){d=g;e=k});Af(this,d,function(g){g instanceof uf?f.cancel():e(g)});return f.then(a,b,c)};X.prototype.$goog_Thenable=!0;var Cf=function(a,b){b instanceof X?Bf(a,x(b.ud,b)):Bf(a,function(){return b})};X.prototype.ud=function(a){var b=new X;Af(this,b.M,b.Nc,b);a&&(b.u=this,this.lb++);return b};
var Df=function(a){return Ca(a.Eb,function(b){return v(b[1])})},wf=function(a){if(a.Ib&&a.N&&Df(a)){var b=a.Ib,c=Ef[b];c&&(p.clearTimeout(c.U),delete Ef[b]);a.Ib=0}a.u&&(a.u.lb--,delete a.u);b=a.L;for(var d=c=!1;a.Eb.length&&!a.Ob;){var e=a.Eb.shift(),f=e[0],g=e[1];e=e[2];if(f=a.Wa?g:f)try{var k=f.call(e||a.Kc,b);q(k)&&(a.Wa=a.Wa&&(k==b||k instanceof Error),a.L=b=k);if(Sd(b)||"function"===typeof p.Promise&&b instanceof p.Promise)d=!0,a.Ob=!0}catch(l){b=l,a.Wa=!0,Df(a)||(c=!0)}}a.L=b;d&&(k=x(a.Jc,
a,!0),d=x(a.Jc,a,!1),b instanceof X?(Af(b,k,d),b.Dc=!0):b.then(k,d));c&&(b=new Ff(b),Ef[b.U]=b,a.Ib=b.U)},xf=function(){z.call(this)};y(xf,z);xf.prototype.message="Deferred has already fired";xf.prototype.name="AlreadyCalledError";var uf=function(){z.call(this)};y(uf,z);uf.prototype.message="Deferred was canceled";uf.prototype.name="CanceledError";var Ff=function(a){this.U=p.setTimeout(x(this.Xd,this),0);this.qb=a};
Ff.prototype.Xd=function(){C(Ef[this.U],"Cannot throw an error that is not scheduled.");delete Ef[this.U];throw this.qb;};var Ef={};var Hf=function(a,b){W.call(this,b);this.a=a;this.Ja=new R(this);Qc(this,sa(Rc,this.Ja));this.aa=new ie(100,this.i());Qc(this,sa(Rc,this.aa));this.C=new X;this.D=new X;this.v=new X;this.Tb=tf();this.ra=null;this.Ga={};this.Nd=this.a.name;Gf(this.a,this.a.name+"_"+Y(this.a));this.Xa=!1;Cf(this.v,this.C);Cf(this.v,this.D);Bf(this.v,this.gc,this);this.v.M(!0);this.Ja.Za(this.aa,"tick",this.$a);P("DirectTransport created. role="+Y(this.a))};y(Hf,W);
var If={},Lf=function(a){var b=new Jf(a.channelName,a.service,a.payload);a=b.Pb;var c=b.pc;b=b.ab;Q(N.c,"messageReceived: channel="+a+", service="+c+", payload="+b);var d=V[a];if(d)return d.ia(c,b),!0;d=Kf(b)[0];for(var e in V){var f=V[e];if(1==Y(f)&&!f.isConnected()&&"tp"==c&&"SETUP"==d)return Gf(f,a),f.ia(c,b),!0}P("channel name mismatch; message ignored.");return!1};h=Hf.prototype;h.Ta=7;
h.Hb=function(a){a=Kf(a);var b=a[1];switch(a[0]){case "SETUP_ACK":this.C.N||this.C.M(!0);break;case "SETUP":this.Db(),null!=this.ra&&this.ra!=b&&(P("Sending SETUP and changing peer ID to: "+b),this.eb()),this.ra=b}};h.eb=function(){this.send("tp","SETUP,"+this.Tb)};h.Db=function(){this.send("tp","SETUP_ACK");this.D.N||this.D.M(!0)};
h.connect=function(){var a=this.i();if(a){var b=pa(a);0==(If[b]||0)&&null==ja("crosswindowmessaging.channel",a)&&ia("crosswindowmessaging.channel",Lf,a);If[b]++;this.Xa=!0;this.$a()}else Q(N.c,"connect(): no window to initialize.")};h.$a=function(){this.a.isConnected()?this.aa.stop():(this.aa.start(),this.eb())};h.send=function(a,b){this.a.R?(a=new Jf(this.Nd+"_"+(0==Y(this.a)?1:0),a,b),this.a.m.directSyncMode?this.Oc(a):this.Ga[pa(a)]=je(x(this.Oc,this,a),0)):Q(N.c,"send(): window not ready")};
h.Oc=function(a){var b=pa(a);this.Ga[b]&&delete this.Ga[b];try{var c=ja("crosswindowmessaging.channel",this.a.R)}catch(d){(a=N.c)&&a.ta("Can't access other window, ignoring.",d);return}if(null===c)(a=N.c)&&a.ta("Peer window had no global function.",void 0);else try{c({channelName:a.Pb,service:a.pc,payload:a.ab}),P("send(): channelName="+a.Pb+" service="+a.pc+" payload="+a.ab)}catch(d){(a=N.c)&&a.ta("Error performing call, ignoring.",d)}};h.gc=function(){Mf(this.a,0)};
h.g=function(){if(this.Xa){var a=this.i(),b=pa(a);1==--If[b]&&ia("crosswindowmessaging.channel",null,a)}this.Ga&&(Ka(this.Ga,function(c){p.clearTimeout(c)}),this.Ga=null);this.C&&(this.C.cancel(),delete this.C);this.D&&(this.D.cancel(),delete this.D);this.v&&(this.v.cancel(),delete this.v);Hf.G.g.call(this)};var Kf=function(a){a=a.split(",");a[1]=a[1]||null;return a},Jf=function(a,b,c){this.Pb=a;this.pc=b;this.ab=c};var Nf=function(a,b){W.call(this,b);this.a=a;this.bb=[];this.zd=x(this.Ad,this)};y(Nf,W);h=Nf.prototype;h.Ta=2;h.mc=!1;h.connect=function(){0==Y(this.a)?(this.ga=this.a.Ma,this.ga.XPC_toOuter=x(this.Uc,this)):this.Bc()};
h.Bc=function(){var a=!0;try{this.ga||(this.ga=this.i().frameElement),this.ga&&this.ga.XPC_toOuter&&(this.hc=this.ga.XPC_toOuter,this.ga.XPC_toOuter.XPC_toInner=x(this.Uc,this),a=!1,this.send("tp","SETUP_ACK"),Mf(this.a))}catch(b){O(N.c,"exception caught while attempting setup: "+b)}a&&(this.Ac||(this.Ac=x(this.Bc,this)),this.i().setTimeout(this.Ac,100))};
h.Hb=function(a){if(0!=Y(this.a)||this.a.isConnected()||"SETUP_ACK"!=a)throw Error("Got unexpected transport message.");this.hc=this.ga.XPC_toOuter.XPC_toInner;Mf(this.a)};h.Uc=function(a,b){this.mc||0!=this.bb.length?(this.bb.push({Td:a,ab:b}),1==this.bb.length&&this.i().setTimeout(this.zd,1)):this.a.ia(a,b)};h.Ad=function(){for(;this.bb.length;){var a=this.bb.shift();this.a.ia(a.Td,a.ab)}};h.send=function(a,b){this.mc=!0;this.hc(a,b);this.mc=!1};
h.g=function(){Nf.G.g.call(this);this.ga=this.hc=null};var Pf=function(a,b){W.call(this,b);this.a=a;this.Od=this.a.m.pru;this.cd=this.a.m.ifrid;uc&&Of()};y(Pf,W);if(uc)var Qf=[],Rf=0,Of=function(){Rf||(Rf=window.setTimeout(function(){Sf()},1E3))},Sf=function(a){var b=ta();for(a=a||3E3;Qf.length&&b-Qf[0].timestamp>=a;){var c=Qf.shift().Id;Ze(c);Ed("iframe removed")}Rf=window.setTimeout(Tf,1E3)},Tf=function(){Sf()};var Uf={};Pf.prototype.Ta=3;Pf.prototype.connect=function(){this.i().xpcRelay||(this.i().xpcRelay=Vf);this.send("tp","SETUP")};
var Vf=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c);b=b.substr(c+1);if(K&&-1!=(c=d.indexOf("|"))){g=d.substr(0,c);d=d.substr(c+1);c=d.indexOf("+");var e=d.substr(0,c);c=parseInt(d.substr(c+1),10);var f=Uf[e];f||(f=Uf[e]={Qc:[],dd:0,Pc:0});-1!=d.indexOf("++")&&(f.Pc=c+1);f.Qc[c]=b;f.dd++;if(f.dd!=f.Pc)return;b=f.Qc.join("");delete Uf[e]}else var g=d;V[a].ia(g,decodeURIComponent(b))};Pf.prototype.Hb=function(a){"SETUP"==a?(this.send("tp","SETUP_ACK"),Mf(this.a)):"SETUP_ACK"==a&&Mf(this.a)};
Pf.prototype.send=function(a,b){b=encodeURIComponent(b);var c=b.length;if(K&&1800<c)for(var d=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^ta()).toString(36),e=0,f=0;e<c;f++){var g=b.substr(e,1800);e+=1800;Wf(this,a,g,d+(e>=c?"++":"+")+f)}else Wf(this,a,b)};
var Wf=function(a,b,c,d){if(K){var e=a.i().document.createElement("DIV"),f={src:null,srcdoc:null},g={onload:new E(Qa,"this.xpcOnload()"),sandbox:null},k={sandbox:""};var l={};for(var m in f)C(m.toLowerCase()==m,"Must be lower case"),l[m]=f[m];for(m in k)C(m.toLowerCase()==m,"Must be lower case"),l[m]=k[m];for(m in g){var n=m.toLowerCase();if(n in f)throw Error('Cannot override "'+n+'" attribute, got "'+m+'" with value "'+g[m]+'"');n in k&&delete l[n];l[m]=g[m]}f=null;g="";if(l)for(B in l){if(!Hb.test(B))throw Error('Invalid attribute name "'+
B+'".');m=l[B];if(null!=m){k=B;n=m;if(n instanceof E)n=Sa(n);else if("style"==k.toLowerCase()){m=void 0;if(!w(n))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof n+" given: "+n);if(!(n instanceof F)){var la="";for(m in n){if(!/^[-_a-zA-Z0-9]+$/.test(m))throw Error("Name allows only [-_a-zA-Z0-9], got: "+m);var A=n[m];null!=A&&(A=u(A)?Ba(A,qb).join(" "):qb(A),la+=m+":"+A+";")}n=la?(new F).pa(la):ob}n instanceof F&&n.constructor===F&&n.od===nb?m=n.yb:
(D("expected object of type SafeStyle, got '"+n+"' of type "+t(n)),m="type_error:SafeStyle");n=m}else{if(/^on/i.test(k))throw Error('Attribute "'+k+'" requires goog.string.Const value, "'+n+'" given.');if(k.toLowerCase()in Ib)if(n instanceof Wa)n=Xa(n).toString();else if(n instanceof ib)n=jb(n).toString();else if(r(n))n=mb(n).T();else throw Error('Attribute "'+k+'" on tag "iframe" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+n+'" given.');}n.ha&&(n=n.T());C(r(n)||ha(n),"String or number value expected, got "+
typeof n+" with value: "+n);k=k+'="'+fb(String(n))+'"';g+=" "+k}}var B="<iframe"+g;g=void 0;null!=g?u(g)||(g=[g]):g=[];!0===Pa.iframe?(C(!g.length,"Void tag <iframe> does not allow content."),B+=">"):(f=Lb(g),B+=">"+Eb(f).toString()+"</iframe>",f=f.Ka());(l=l&&l.dir)&&(f=/^(ltr|rtl|auto)$/i.test(l)?0:null);l=Fb(B,f);if(Mb[e.tagName.toUpperCase()])throw Error("goog.dom.safe.setInnerHtml cannot be used to set content of "+e.tagName+".");if(Nb())for(;e.lastChild;)e.removeChild(e.lastChild);e.innerHTML=
Eb(l);e=e.childNodes[0];e.xpcOnload=Xf}else e=a.i().document.createElement("IFRAME"),uc?Qf.push({timestamp:ta(),Id:e}):kd(e,"load",Xf);l=e.style;l.visibility="hidden";l.width=e.style.height="0px";l.position="absolute";l=a.Od;l+="#"+a.a.name;a.cd&&(l+=","+a.cd);l+="|"+b;d&&(l+="|"+d);l+=":"+c;e.src=l;a.i().document.body.appendChild(e);Ed("msg sent: "+l)},Xf=function(){Ed("iframe-load");Ze(this)};Pf.prototype.g=function(){Pf.G.g.call(this);uc&&Sf(0)};var Z=function(a,b,c,d,e){W.call(this,c);this.a=a;this.W=e||2;C(1<=this.W);C(2>=this.W);this.bd=b||"*";this.Ja=new R(this);this.aa=new ie(100,this.i());this.wb=!!d;this.C=new X;this.D=new X;this.v=new X;this.Tb=tf();this.ra=null;this.wb?1==Y(this.a)?Cf(this.v,this.C):Cf(this.v,this.D):(Cf(this.v,this.C),2==this.W&&Cf(this.v,this.D));Bf(this.v,this.gc,this);this.v.M(!0);this.Ja.Za(this.aa,"tick",this.$a);P("NativeMessagingTransport created.  protocolVersion="+this.W+", oneSidedHandshake="+this.wb+
", role="+Y(this.a))};y(Z,W);Z.prototype.F=null;Z.prototype.Xa=!1;Z.prototype.Ta=1;var Yf={};Z.prototype.fb=0;
var ag=function(a){var b=a.na.data;if(!r(b))return!1;var c=b.indexOf("|"),d=b.indexOf(":");if(-1==c||-1==d)return!1;var e=b.substring(0,c);c=b.substring(c+1,d);b=b.substring(d+1);Q(N.c,"messageReceived: channel="+e+", service="+c+", payload="+b);if(d=V[e])return d.ia(c,b,a.na.origin),!0;d=Zf(b)[0];for(var f in V){var g=V[f];if(1==Y(g)&&!g.isConnected()&&"tp"==c&&("SETUP"==d||"SETUP_NTPV2"==d)&&$f(g,a.na.origin))return Gf(g,e),g.ia(c,b),!0}P('channel name mismatch; message ignored"');return!1};
Z.prototype.Hb=function(a){var b=Zf(a);a=b[1];switch(b[0]){case "SETUP_ACK":bg(this,1);this.C.N||this.C.M(!0);break;case "SETUP_ACK_NTPV2":2==this.W&&(bg(this,2),this.C.N||this.C.M(!0));break;case "SETUP":bg(this,1);this.Db(1);break;case "SETUP_NTPV2":2==this.W&&(b=this.F,bg(this,2),this.Db(2),1!=b&&null==this.ra||this.ra==a||(P("Sending SETUP and changing peer ID to: "+a),this.eb()),this.ra=a)}};
Z.prototype.eb=function(){C(!(1==this.W&&2==this.F));2!=this.W||null!=this.F&&2!=this.F||this.send("tp","SETUP_NTPV2,"+this.Tb);null!=this.F&&1!=this.F||this.send("tp","SETUP")};Z.prototype.Db=function(a){C(1!=this.W||2!=a,"Shouldn't try to send a v2 setup ack in v1 mode.");if(2!=this.W||null!=this.F&&2!=this.F||2!=a){if(null!=this.F&&1!=this.F||1!=a)return;this.send("tp","SETUP_ACK")}else this.send("tp","SETUP_ACK_NTPV2");this.D.N||this.D.M(!0)};
var bg=function(a,b){b>a.F&&(a.F=b);1==a.F&&(a.D.N||a.wb||a.D.M(!0),a.ra=null)};h=Z.prototype;h.connect=function(){var a=this.i(),b=pa(a),c=Yf[b];ha(c)||(c=0);0==c&&kd(a.postMessage?a:a.document,"message",ag,!1,Z);Yf[b]=c+1;this.Xa=!0;this.$a()};h.$a=function(){var a=0==Y(this.a);this.wb&&a||this.a.isConnected()||this.ma?this.aa.stop():(this.aa.start(),this.eb())};
h.send=function(a,b){var c=this.a.R;c?(this.send=function(d,e){var f=this,g=this.a.name;this.fb=je(function(){f.fb=0;try{var k=c.postMessage?c:c.document;if(k.postMessage)k.postMessage(g+"|"+d+":"+e,f.bd),Q(N.c,"send(): service="+d+" payload="+e+" to hostname="+f.bd);else{var l=N.c;l&&l.ta("Peer window had no postMessage function.",void 0)}}catch(m){(k=N.c)&&k.ta("Error performing postMessage, ignoring.",m)}},0)},this.send(a,b)):Q(N.c,"send(): window not ready")};
h.gc=function(){Mf(this.a,1==this.W||1==this.F?200:void 0)};h.g=function(){if(this.Xa){var a=this.i(),b=pa(a),c=Yf[b];Yf[b]=c-1;1==c&&rd(a.postMessage?a:a.document,"message",ag,!1,Z)}this.fb&&(p.clearTimeout(this.fb),this.fb=0);Rc(this.Ja);delete this.Ja;Rc(this.aa);delete this.aa;this.C.cancel();delete this.C;this.D.cancel();delete this.D;this.v.cancel();delete this.v;delete this.send;Z.G.g.call(this)};var Zf=function(a){a=a.split(",");a[1]=a[1]||null;return a};var cg=function(a,b){W.call(this,b);this.a=a;this.Cc=a.at||"";this.fd=a.rat||"";a=this.i();if(!a.nix_setup_complete)try{a.execScript("Class GCXPC____NIXVBS_wrapper\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport.GCXPC____NIXJS_handle_message(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport.GCXPC____NIXJS_create_channel(channel)\nEnd Sub\nPublic Sub GCXPC____NIXVBS_container()\n End Sub\nEnd Class\n Function GCXPC____NIXVBS_get_wrapper(transport, auth)\nDim wrap\nSet wrap = New GCXPC____NIXVBS_wrapper\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet GCXPC____NIXVBS_get_wrapper = wrap\nEnd Function",
"vbscript"),a.nix_setup_complete=!0}catch(c){O(N.c,"exception caught while attempting global setup: "+c)}this.GCXPC____NIXJS_handle_message=this.Hd;this.GCXPC____NIXJS_create_channel=this.xd};y(cg,W);h=cg.prototype;h.Ta=6;h.Oa=!1;h.qa=null;h.connect=function(){0==Y(this.a)?this.zc():this.yc()};
h.zc=function(){if(!this.Oa){var a=this.a.Ma;try{a.contentWindow.opener=(0,this.i().GCXPC____NIXVBS_get_wrapper)(this,this.Cc),this.Oa=!0}catch(b){O(N.c,"exception caught while attempting setup: "+b)}this.Oa||this.i().setTimeout(x(this.zc,this),100)}};
h.yc=function(){if(!this.Oa){try{var a=this.i().opener;if(a&&"GCXPC____NIXVBS_container"in a){this.qa=a;if(this.qa.GetAuthToken()!=this.fd){O(N.c,"Invalid auth token from other party");return}this.qa.CreateChannel((0,this.i().GCXPC____NIXVBS_get_wrapper)(this,this.Cc));this.Oa=!0;Mf(this.a)}}catch(b){O(N.c,"exception caught while attempting setup: "+b);return}this.Oa||this.i().setTimeout(x(this.yc,this),100)}};
h.xd=function(a){"unknown"==typeof a&&"GCXPC____NIXVBS_container"in a||O(N.c,"Invalid NIX channel given to createChannel_");this.qa=a;this.qa.GetAuthToken()!=this.fd?O(N.c,"Invalid auth token from other party"):Mf(this.a)};h.Hd=function(a,b){this.i().setTimeout(x(function(){this.a.ia(a,b)},this),1)};h.send=function(a,b){"unknown"!==typeof this.qa&&O(N.c,"NIX channel not connected");this.qa.SendMessage(a,b)};h.g=function(){cg.G.g.call(this);this.qa=null};var eg=function(a,b){pf.call(this);for(var c=0,d;d=rf[c];c++)if(d in a&&!/^https?:\/\//.test(a[d]))throw Error("URI "+a[d]+" is invalid for field "+d);this.m=a;this.name=this.m.cn||tf();this.Z=b||ua||(ua=new $e);this.pb=[];this.jc=new R(this);a.lpu=a.lpu||te(this.Z.i().location.href)+"/robots.txt";a.ppu=a.ppu||te(a.pu||"")+"/robots.txt";V[this.name]=this;td(window,"unload",dg)||jd(window,"unload",dg);P("CrossPageChannel created: "+this.name)};y(eg,pf);var fg=/^%*tp$/,gg=/^%+tp$/;h=eg.prototype;
h.la=null;h.Ca=null;h.H=null;h.f=1;h.isConnected=function(){return 2==this.f};h.R=null;h.Ma=null;h.connect=function(a){this.Qb=a||ka;3==this.f&&(this.f=1);this.Ca?Bf(this.Ca,this.Ic):this.Ic()};
h.Ic=function(){P("continueConnection_()");this.Ca=null;if(this.m.ifrid){var a=this.m.ifrid;this.Ma=r(a)?this.Z.Ua.getElementById(a):a}this.Ma&&((a=this.Ma.contentWindow)||(a=window.frames[this.m.ifrid]),this.R=a);if(!this.R){if(window==window.top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");this.R=window.parent}if(!this.H){if(!this.m.tp){a=this.m;if(v(document.postMessage)||v(window.postMessage)||K&&window.postMessage)var b=1;else if(tc)b=2;else if(K&&this.m.pru)b=
3;else{var c;if(c=K){c=!1;try{b=window.opener,window.opener={},c=oc(window,"opener"),window.opener=b}catch(d){}}b=c?6:0}a.tp=b}if(v(this.m.tp))this.H=new this.m.tp(this,this.Z);else switch(this.m.tp){case 1:this.H=new Z(this,this.m.ph,this.Z,!!this.m.osh,this.m.nativeProtocolVersion||2);break;case 6:this.H=new cg(this,this.Z);break;case 2:this.H=new Nf(this,this.Z);break;case 3:this.H=new Pf(this,this.Z);break;case 7:if(a=this.R)try{a=window.document.domain==this.R.document.domain}catch(d){a=!1}a?
this.H=new Hf(this,this.Z):P("DirectTransport not supported for this window, peer window in different security context or not set yet.")}if(this.H)P("Transport created: "+this.H.getName());else throw Error("CrossPageChannel: No suitable transport found! You may try injecting a Transport constructor directly via the channel config object.");}for(this.H.connect();0<this.pb.length;)this.pb.shift()()};
h.close=function(){this.Ca&&(this.Ca.cancel(),this.Ca=null);this.pb.length=0;this.jc.cb();this.f=3;Rc(this.H);this.Qb=this.H=null;Rc(this.la);this.la=null;P('Channel "'+this.name+'" closed')};var Mf=function(a,b){a.isConnected()||a.la&&a.la.ac()||(a.f=2,P('Channel "'+a.name+'" connected'),Rc(a.la),q(b)?(a.la=new of(a.Qb,b),a.la.start()):(a.la=null,a.Qb()))};
eg.prototype.send=function(a,b){if(this.isConnected()){try{var c=!!this.R&&!this.R.closed}catch(d){c=!1}c?(w(b)&&(b=(new zd).Fb(b)),this.H.send(hg(a),b)):(O(N.c,"Peer has disappeared."),this.close())}else O(N.c,"Can't send. Channel not connected.")};
eg.prototype.ia=function(a,b,c){if(this.Ca)this.pb.push(x(this.ia,this,a,b,c));else if($f(this,c))if(this.ma||3==this.f)(b=N.c)&&b.ta("CrossPageChannel::xpcDeliver(): Channel closed.",void 0);else if(a&&"tp"!=a)if(this.isConnected()){if(c=a.replace(/%[0-9a-f]{2}/gi,decodeURIComponent),c=gg.test(c)?c.substring(1):c,a=this.qc[c],a||(this.Lc?a={M:sa(this.Lc,c),Yc:w(b)}:((a=this.c)&&a.ta('Unknown service name "'+c+'"',void 0),a=null)),a){a:{var d=a.Yc;if(d&&r(b))try{var e=JSON.parse(b);break a}catch(f){(e=
this.c)&&e.ta("Expected JSON payload for "+c+', was "'+b+'"',void 0);e=null;break a}else if(!d&&!r(b)){e=(new zd).Fb(b);break a}e=b}null!=e&&a.M(e)}}else P("CrossPageChannel::xpcDeliver(): Not connected.");else this.H.Hb(b);else(b=N.c)&&b.ta('Message received from unapproved origin "'+c+'" - rejected.',void 0)};
var hg=function(a){fg.test(a)&&(a="%"+a);return a.replace(/[%:|]/g,encodeURIComponent)},Y=function(a){var b=a.m.role;return ha(b)?b:window.parent==a.R?1:0},Gf=function(a,b){Q(N.c,"changing channel name to "+b);delete V[a.name];a.name=b;V[b]=a},$f=function(a,b){var c=a.m.ph;return/^[\s\xa0]*$/.test(null==b?"":String(b))||/^[\s\xa0]*$/.test(null==c?"":String(c))||b==a.m.ph};eg.prototype.g=function(){this.close();this.Ma=this.R=null;delete V[this.name];Rc(this.jc);delete this.jc;eg.G.g.call(this)};
var dg=function(){for(var a in V)Rc(V[a])};var ig=function(a,b,c,d,e){a=new S(a);0!=b&&(T(a),a.B.set("authuser",b));null!=c&&(T(a),a.B.set("pageId",c));null!=d&&(T(a),a.B.set("service",d));this.Ud=a.toString();this.ya=e;this.Ld=0};ig.prototype.start=function(){};ig.prototype.send=function(a,b,c){var d=new S(this.Ud);for(g in c){var e=g,f=c[g];T(d);d.B.set(e,f)}c=d.toString();d=x(this.Sc,this,this.Ld++);var g=new U;Le.push(g);d&&g.Za("complete",d);g.cc("ready",g.wd);g.vc=!0;g.send(c,"POST",a,b)};
ig.prototype.Sc=function(a,b){b=b.target;Ue(b)?this.ya.va.send("ss",[a]):(b=We(b),this.ya.va.send("sf",[a,b]))};var jg=function(a,b,c,d,e){this.Gd=new ig(a,b,c,d,this);a=new S(e||window.location.href);this.ae=JSON.parse(a.B.get("xpc")||"");this.va=null};jg.prototype.$b=function(){this.va=new eg(this.ae);var a=x(jg.prototype.send,this);this.va.qc.s={M:a,Yc:!0};this.va.connect()};jg.prototype.send=function(a){this.Gd.send(a[0],a[1],a[2])};jg.prototype.Sc=function(a,b){b=b.target;Ue(b)?this.va.send("ss",[a]):this.va.send("sf",[a,We(b)])};jg.prototype.init=jg.prototype.$b;ia("invalidation.XpcSenderServer",jg,void 0);
